### ISSUE TITLE
Infinite request to proxytown in Gatsbyjs

### ISSUE THREAD

**Issue by chesteralan** [QwikDev/partytown#121]
Site is sending infinite request to proxytown.

https://6238d978bd85b100081eccd2--prod-builder-gatsby-funnel.netlify.app/probiotic-chews

Video recording: https://monosnap.com/file/DevVjozZn3QMqApDirxVqZMARpuog3

Go to Network in Devtools

Source Code: https://github.com/chesteralan/gatsby-plugin-partytown

Forgive me with the description. It's my first time to post an issue.

**Comment by Kinbaum** [comment]
Hello, same thing happens using Next.js `worker` strategy and Adobe analytics

**Comment by codesprint** [comment]
same thing happens here with react.

**Comment by Brunight** [comment]
Same here... Any news?

**Comment by ymeghna** [comment]
I followed created reverse proxy for partytown using  https://nystudio107.com/blog/creating-a-reverse-proxy-for-partytown-with-aws-cloudfront
And then infinite proxytown calls happened

**Comment by ymeghna** [comment]
Facing the same issue
I followed created reverse proxy for partytown using https://nystudio107.com/blog/creating-a-reverse-proxy-for-partytown-with-aws-cloudfront
And then infinite proxytown calls happened

**Comment by ymeghna** [comment]
Facing the same issue
I created reverse proxy for partytown using https://nystudio107.com/blog/creating-a-reverse-proxy-for-partytown-with-aws-cloudfront
And then infinite proxytown calls happened

**Comment by jonathanlemonsonos** [comment]
seeing the same thing in next 12.3.1 on vercel

**Comment by danestves** [comment]
> Facing the same issue I created reverse proxy for partytown using [nystudio107.com/blog/creating-a-reverse-proxy-for-partytown-with-aws-cloudfront](https://nystudio107.com/blog/creating-a-reverse-proxy-for-partytown-with-aws-cloudfront) And then infinite proxytown calls happened

Question, you made it for all the scripts? I only made it for one, but I have two scripts right now, so if I make the proxy for all the scripts the infinite request should disappear right?

**Comment by danestves** [comment]
Seeing the same issue here

**Comment by kubica4u2** [comment]
I am having the same issue with Fullstory. Any update on this issue?

**Comment by vasikaranb-nagarro** [comment]
Same issue with svelte. Any update on this issue?

**Comment by jackeverydayzero** [comment]
Same issue
