### ISSUE TITLE
Use Functions exported through GTM

### ISSUE THREAD

**Issue by sandeshpe** [QwikDev/partytown#139]
I need to use a function which I've exported in one of the tag. This tag is called on every page load, so that the util method written can be exposed to others tag.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/90243898/160684458-4840faca-1f7f-4c49-a027-5fad605fe5ec.png">

**Comment by gioboa** [comment]
Did you solve the problem? I think [forwarding-events](https://partytown.builder.io/forwarding-events) can solve your issue.
