### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object - partytown-sandbox-sw.js

### ISSUE THREAD

**Issue by jhonatantft** [QwikDev/partytown#198]
**Describe the bug**
I tried to integrate partytown to an ecommerce website (VTEX platform) following the [HTML integration doc](https://partytown.builder.io/html), and all the resources are being loaded but I'm getting this error that is preventing the code to be executed. 

````
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at readOwnImplementation (partytown-sandbox-sw.js?v=0.6.1:476:38)
    at partytown-sandbox-sw.js?v=0.6.1:462:75
    at Array.map (<anonymous>)
    at readImplementations (partytown-sandbox-sw.js?v=0.6.1:462:19)
    at readMainPlatform (partytown-sandbox-sw.js?v=0.6.1:434:27)
    at partytown-sandbox-sw.js?v=0.6.1:526:56
    at worker.onmessage (partytown-sandbox-sw.js?v=0.6.1:536:69)
````

**Partytown version**
"@builder.io/partytown": "^0.6.1"

**Screenshots**

![image](https://user-images.githubusercontent.com/20176235/173649728-53b44c36-71f0-4698-816d-0481a1299581.png)

**Additional context**

The code breaks because it tries to use the `Object.getPrototypeOf` with an `undefined` type as you can see in the screenshot below. The method `readOwnImplementation` from **partytown-sandbox-sw.js** tries to get the prototype but it does not have any validation before doing it, so it breaks. I highlighted the method in yellow and where the param is coming from.

![image](https://user-images.githubusercontent.com/20176235/173656417-58b81b1c-d859-461a-af1b-c55b3c0d85c2.png)

**Comment by mhevery** [comment]
Thanks, we are running a bit behind right now with a related project. Is this still an issue?

**Comment by jhonatantft** [comment]
Yes, it is @mhevery

**Comment by adamdbradley** [comment]
Are you able to debug which API is crashing? What's the code running before this error happens?

**Comment by AkshayKumar007** [comment]
Hey, just wanted to confirm whether the open bug is related to the issue I'm facing while integrating Partytown in my React Application. 
I'm getting non stop errors getting printed in console causing my app to crash.
It's mainly due to my app not being able to find the third party scripts since I changed their type to `text/partytown`.
The errors are mostly like: `Uncaught TypeError: Cannot read properties of undefined (reading 'then')`, `TypeError: Cannot read properties of undefined (reading 'apply')`, etc.

I included the following script at top after loading partytown in `public/` directory.

```
<script src="~partytown/partytown.js"></script>
```

![image](https://user-images.githubusercontent.com/35987800/218453748-4b373c83-aac4-4dcb-b6f3-add78db40003.png)

**Comment by joepagan** [comment]
@AkshayKumar007 I just had that issue where I was forwarding both datalayer and fbq events, however, I wasn't loading the facebook tracking script, only GA. I would still says that's a bug though.

**Comment by chasegiunta** [comment]
I've got partytown working almost flawlessly if not for this issue. For us, it's stemming from calling `gtag`/`window.gtag`, like `gtag('config', ...options...)` or `gtag('set', ...options...)`.  Both `gtag` & `window.gtag` (just to be safe) are listed in the partytown forward array.

**Comment by jon301** [comment]
Same issue here: 
![image](https://github.com/BuilderIO/partytown/assets/122108/b416cbc7-265f-4a74-85ad-5f08d78c4354)

I have used the ["Copy Library Files" instructions](https://partytown.builder.io/nextjs#copy-library-files) in my NextJS application.

Then configured partytown like this, as i'm using google analytics, gtm and fb pixel in my app:

```js
import { Partytown } from "@builder.io/partytown/react";

...

<Partytown
  forward={["dataLayer.push", "fbq", "gtag"]}
  resolveUrl={(url, location, type) => {
    // ...
  }
/>
```
