### ISSUE TITLE
Facing issue while integrating PartyDown

### ISSUE THREAD

**Issue by ankitguptartpl** [QwikDev/partytown#205]
**Describe the bug**
Getting error when partydown try to render  doubleclick floodlight tag's response. 
`var axel=Math.random() +"",a=1E13*axel;document.write('\x3ciframe src\x3d"https://4914179.fls.doubleclick.net/activityi;src\x3d4914179;type\x3dinvmedia;cat\x3dularc0;dc_lat\x3d;dc_rdid\x3d;tag_for_child_directed_treatment\x3d;tfua\x3d;npa\x3d;ord\x3d'+a+'?" width\x3d"1" height\x3d"1" frameborder\x3d"0" style\x3d"display:none"\x3e\x3c/iframe\x3e');`

**Partytown version**
What version of Partytown you are using, e.g. `0.6.1`

**Screenshots**
![image](https://user-images.githubusercontent.com/12409183/175227407-b3bd7de4-ac1b-4abd-9ee2-9e07be146a65.png)

**Additional context**
Please share if anything I can do to resolve above issue

**Comment by mhevery** [comment]
We need a way to reproduce the issue otherwise there is not much we can do. Please provide a simple reproduction.
