### ISSUE TITLE
Recaptcha v3 fails with "Error: mozRequestAnimationFrame not on global?", any help?

### ISSUE THREAD

**Issue by gremo** [QwikDev/partytown#209]
This is my first time with partytown. I'm try to load Recaptcha v3 script into the worker thread.

This is the partytown configuration in the `<head>`:

```html
<script>
  partytown = {
    resolveUrl(url, location) {
      if ([
        'www.google.com',
      ].includes(url.hostname)) {
        const proxyUrl = new URL("https://cdn.builder.io/api/v1/proxy-api");
        proxyUrl.searchParams.append("url", url);

        return proxyUrl;
      }
    },
    debug: true,
  };
</script>
```

And I'm loading Recaptcha v3 at the `<body>` bottom (site key XXX):

```html
<script type="text/partytown" src="https://www.google.com/recaptcha/api.js?render=XXX&hl=it"></script>
```

The Recaptcha script seems to load fine (no CORS errors)... but as soon as it loads, I get the error:

> Error: mozRequestAnimationFrame not on global?

![Recatpcha error](https://user-images.githubusercontent.com/1532616/177311748-269c7a88-87cf-431a-98d6-1831ca153105.png)

Adding `forward: ["mozRequestAnimationFrame"`] doesn't help at all.

**Comment by charisTheo** [comment]
+1

Replicated the issue:

* Live URL: https://nextjs-recaptcha-partytown-n5szrlcww-charistheo.vercel.app/
* Code on Github repo (partytown branch): https://github.com/charisTheo/nextjs-recaptcha-partytown/tree/partytown

`forward: ["mozRequestAnimationFrame"]` doesn't seem to work for me either, even having `globalThis.mozRequestAnimationFrame = window.requestAnimationFrame` before the partytown configuration script tag. 
`mozRequestAnimationFrame` seems to be set fine after checking in DevTools but still Recaptcha V3 script is complaining.

**Comment by LynxTR** [comment]
Is there any update or workaround about this?
