### ISSUE TITLE
[Nextjs] Tracking event 3rd scripts not tracking all the events

### ISSUE THREAD

**Issue by steven-ruiz** [QwikDev/partytown#210]
**Describe the bug**

- I started using party town to speed up my application, but I noticed that after setting everything up for my 3rd party scripts and loading them within the web worker, tracking events wasn't behaving the same way, I was losing events.

- This issue happened using Nextjs + React the configuration was used in a combination of the Script component from NextJs with the worker strategy

**To Reproduce**

1. Configure PartyTown for GA and Mixpanel to track **_pageview_**
2. Make sure scripts are loaded via web worker
3. Start navigating the website and check every pageview event is tracked

The second way to verify the lack of tracking events:

1. Configure PartyTown for GA and Mixpanel to track **_pageview_**
2. Configure a secondary script for GA and Mixpanel but load the scripts in the main thread with no party town
3. Verify metrics after 24hrs and confirm that the events tracked by using PartyTown are less than using the main thread.

**Reproduction link**
Since these are tracking events scripts I don't have a way to reproduce this in an online tool

**Expected behavior**
The intention is to track every event.

**Partytown version**
Partytown V0.6.0

**Comment by misikoff** [comment]
This only happens for me on particular combinations of Next.js versions and Partytown versions.
The combo of Next.js 12.1.6 and partytown 0.6.1 appears to work properly for me.

**Comment by piyushpriyadarshi** [comment]
@misikoff can you please share the working code for tracking the events once we run the mixpanel into the webworker, i am able to run it in web worker but not able to access using global window object, can you please help me

**Comment by mikkpokk** [comment]
Same issue with Remix, realtime events dropped over 90% after migrating Partytown. 

All my events from desktop come through but from iOS GA4 does not show any realtime information. While debugging network tab, it shows requests going through. Just GA4 registers only inital load events in some weird reason.
