### ISSUE TITLE
new Image call by twitter-ads does not create HTML element

### ISSUE THREAD

**Issue by ghost** [QwikDev/partytown#215]
- [x] I am interested in helping provide a fix!

**Describe the bug**
[Twitter ADS UWT](https://static.ads-twitter.com/uwt.js) throws error when it tries to create image `e` with `new Image()` and then access `display` on `e.style` (`el.style.display = 'none'`); This thrown error seems to block other scripts from being executed.

**To Reproduce**
1. Clone 'npm run dev'
2. Open `localhost:3000`
3. Open console

**Reproduction link**
Couldn't get [Codesandbox](https://codesandbox.io/s/infallible-visvesvaraya-bqdl65) to run, so it's probably better to clone the repo. Included link just in case you get it working.

**Expected behavior**
No errors being thrown, image being added normally. Other scripts should execute.

**Partytown version**
`^0.6.1`

**Comment by dbashford** [comment]
Experiencing the same issue

<img width="757" alt="image" src="https://user-images.githubusercontent.com/581127/181369057-d1f4c93d-46ef-4d6d-a7ff-2ab826fff9f1.png">

**Comment by akselander** [comment]
Commenting for visibility as I've merged my two accounts into one and it untracked all PRs.
