### ISSUE TITLE
[Bug] document.createRange does not work properly

### ISSUE THREAD

**Issue by itxch** [QwikDev/partytown#273]
- [x] I am interested in helping provide a fix! - **Though I've got no clue where I'd start with this, so any pointers would be much appriciated.**

**Describe the bug**
`document.createRange()` methods don't work. Trying to add an element to the DOM using [selectNode](https://developer.mozilla.org/en-US/docs/Web/API/Range/selectNode) and [createContextualFragment](https://developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment) does not work. 

The exact same code works when ran without partytown.

**To Reproduce**
1. Go to https://empty-wave-2618.fly.dev/
2. The text that should be visible (added by script.js) is not.

**Reproduction link**
- Repo: https://github.com/itxch/issues/tree/issue/create-range
   - To reproduce locally, clone and run `npx http-server .`.
- Link: https://empty-wave-2618.fly.dev/

**Expected behavior**
The text "Hello there :)" should be visible on the page.

**Partytown version**
v0.7.0 (latest at time of writing)

**Additional context**
Issue could be that that the `Range` has a commonAncestorContainer that is `#document` rather than body which seems to be the browser default. And even when using [selectNode](https://developer.mozilla.org/en-US/docs/Web/API/Range/selectNode) it cant be changed.

**Comment by itxch** [comment]
@adamdbradley would be great to get your input/thoughts on this one

**Comment by ilja-gusiatin** [comment]
Wondering if this can be reopened or new issue should be raised?
Just hit the same issue.

`createRange` returns different shape objects in browser and worker

using v0.11.0
