### ISSUE TITLE
Huspot integration not working

### ISSUE THREAD

**Issue by DevMentine** [QwikDev/partytown#288]
<!-- 

                      THIS ISSUE WILL BE CLOSED
             (unless there is a high quality reproduction)

We can only help you if you provide us a good reproduction of the problem! 
We are verry sorry but a stack trace or "it does not work" simply does not 
have enough usefull information for us to help you.

Unless we can reproduce the issue in under 1 minute it will be closed as 
can't reproduce!

Your reproduction must have these:
1. an easy way to reproduce the failure on our computers
  - github repo for us to clone OR
  - fork https://replit.com/@MiskoHevery/Partytown-Example
2. exact steps on what to do to cause an error
3. exact steps to retrieve the failure

--!>

- [ ] I am interested in helping provide a fix!

**Describe the bug**
I adapted the example for Hubspot forms on my own site, but it doesn't work.

**To Reproduce**
1. Go to https://mentine-partytown.mentine.work/test-partytown/?partytown=true
2. See if the Hubspot form is shown (after "Hubspot Forms" red title)

**Reproduction link**
https://mentine-partytown.mentine.work/test-partytown/?partytown=true

**Expected behavior**
According to the example (https://github.com/BuilderIO/partytown/blob/main/tests/integrations/hubspot/forms.html), it should work. If I load the scripts with the classic attribute type="text/javascript" the form is visible, see: https://mentine-partytown.mentine.work/test-partytown/?partytown=false

**Partytown version**
0.7.1 (inlined code)

**Additional context**
I also integrated the example for GTM, which apparently works but doesn't actually track events. The GTM debugger can't even connect to the site, with error: Could not connect to XXX. A timeout occurred while attempting to connect to XXX". Again, this works using the version with Parytown script type disabled (querystring parameter partytown=false).

Thanks for all you do. Any help will be appreciated. Let me know if more details are needed.

**Comment by DevMentine** [comment]
I don't understand why I lost the formatting of the message, sorry.

**Comment by DevMentine** [comment]
I don't understand why I lost the formatting of the message, sorry.

**Comment by robsongajunior** [comment]
Did you have problem with hubspot forms or another?
