### ISSUE TITLE
Pass environment to partytown `resolveUrl` config to make multiple env reverse proxy

### ISSUE THREAD

**Issue by harrytran998** [QwikDev/partytown#310]
**Is your feature request related to a problem? Please describe.**
When we config `resolveUrl(url)` to make some reverse proxy. Bcs we have a lot of environment, EX:
In UAT(user acceptant test) env, we want the reverse proxy server to be `A`. But in production, it might become `B`.

**But we cannot pass the environment outside into `resolveUrl()`**

**Describe the solution you'd like**
Maybe pass the ENV in the partytown config. Then use callback in the top config like

```js
partytow =  {
	debug: env.dev === 'true',
	env: ENV,
    resolveUrl(url, config) {
		const env = config.env;
    }
}
```

**Comment by nandazman** [comment]
any update on this ?
