### ISSUE TITLE
Intercom integration is not working, scrollTop set property error

### ISSUE THREAD

**Issue by sameer-khaan** [QwikDev/partytown#314]
- [ ] I am interested in helping provide a fix!

**Describe the bug**
Whenever I click on start message it appears for mili seconds and boom "Uncaught TypeError: Cannot set property scrollTop of [object Object] which has only a getter" event error occurs.

**To Reproduce**
1. Click on Intercom icon
2. Click on messages icon on bottom
3. Now click on 'send us a message' button
4. See error on console

**Reproduction link**
https://codesandbox.io/s/happy-http-j1ob3c?file=/index.html
https://j1ob3c.csb.app/

**Expected behavior**
I want Intercom messages to work with partytown as it was working without it.

**Partytown version**
What version of Partytown you are using, e.g. `0.7.3`

**Screenshots**
![Screenshot from 2022-12-09 12-48-20](https://user-images.githubusercontent.com/10200125/206653847-36682f3a-6046-4c28-aeb8-82632a5bd4cc.png)

**Comment by maplessmann** [comment]
We are having the same issue!

@adamdbradley do you know what we can do to work around this error?

**Comment by shaiq-dev** [comment]
@sameer-khaan I checked your codesandox, you haven't forwarded the events. You can check the docs about event forwarding. This can be the cause for the error but I am not sure.

**Comment by beltran120394** [comment]
We are experiencing an identical problem 😭 

@adamdbradley, Do you have any suggestions on how we can resolve this error?
