### ISSUE TITLE
Partytown throws errors when GTM script is integrated

### ISSUE THREAD

**Issue by JoeLim13** [QwikDev/partytown#330]
This is the GTM script I integrated:

```
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXXXX');</script>

```

and partytown throws errors as below:

<img width="593" alt="Screenshot 2022-12-22 at 9 08 40 PM" src="https://user-images.githubusercontent.com/75823736/209141256-5c4255db-8dde-42d8-9768-00db3aeb946e.png">

**Comment by JoeLim13** [comment]
Hi @jonathan-dejong, thanks for replying! May I know how to move other third party services out of GTM? I was given this GTM script, should I modify the script?

**Comment by jonathan-dejong** [comment]
No you would remove those tags from within the Google tag Manager interface. Then you would add the scripts you removed in some other way. For example by placing them in an appropriate file location in your website codebase. 
However if you aren't comfortable with that I'd recommend hiring a developer or not using Partytown for GTM. 

I've now implemented Partytown on two of our client sites and it really is not a plug-and-play thing. Make sure you're up for the challenge if you want to play with it ☺️
