### ISSUE TITLE
How can I integrate matomo analytics?

### ISSUE THREAD

**Issue by rrolla** [QwikDev/partytown#333]
**Is your feature request related to a problem? Please describe.**
I want to use this fantastic idea to offload main thread for matomo analytics

**Describe the solution you'd like**
Help to understand how can I integrate it with code examples, and update [forwarding events](https://partytown.builder.io/forwarding-events) documentation with advanced cases

**Describe alternatives you've considered**
Point to some similar integration

**Additional context**
JavaScript Tracking Client for matomo https://developer.matomo.org/guides/tracking-javascript-guide

I added scripts

```html

<script>
  partytown = {
    debug: true,
    forward: ["_paq.push"],
    lib: "/~partytown/",
    logCalls: true,
    logGetters: true,
    logSetters: true,
    logImageRequests: true,
    logMainAccess: true,
    logScriptExecution: true,
    logSendBeaconRequests: true,
    logStackTraces: true
  };
</script>

<script>
  window._paq = [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);
  _paq.push(["setTrackerUrl", "https://stats.example.com/matomo.php"]);
  _paq.push(["setSiteId", "14"]);
</script>
<script src="https://stats.example.com/matomo.js" async type="text/partytown"></script>
```

I also fixed issues with cors, so that mean web worker can fetch my analytics script because there are no more errors about cors

But cannot understand how can I forward push to array with value `'trackPageView'` eg:
```js
_paq.push(['trackPageView']);
```

If I execute manually on console it throws error

```js
  _paq.push(['trackPageView']); 
```

```js
_paq.push() was used but Matomo tracker was not initialized before the matomo.js file was loaded. Make sure to configure the tracker via _paq.push before loading matomo.js. Alternatively, you can create a tracker via Matomo.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order. 
Array [ "trackPageView" ]
```
Looks like party town itself loads, but cannot send anything to matomo
![image](https://user-images.githubusercontent.com/3932546/210065420-6fd0bb94-9ac0-4e87-b246-045fe063f776.png)

**Comment by mhoev** [comment]
@rrolla, did you make by chance any progress in this?
Thank you!

**Comment by rrolla** [comment]
> @rrolla, did you make by chance any progress in this?
> Thank you!

No unfortunately no progress on this, I added in old way for now.

**Comment by slamer59** [comment]
Hello, I am also interested. If someone could guide us to make it work ?

**Comment by AlejandroAkbal** [comment]
I'm interested in this, please let me know of a solution

**Comment by nekochan0122** [comment]
I'm also facing this issue, any update?

**Comment by woldtwerk** [comment]
> I'm also facing this issue, any update?

got this from matomo:

> Currently we do not sent access control headers with our JS files but this is something we are considering doing.
> 
> We have had several requests and made it a priority issue.

But I wouldn't get my hopes up. The rest of the support ticket indicates, that they don't really know what partytown is or what the header does.
In there opinion csp setting of the site is wrong 🫠

**Comment by gioboa** [comment]
Thanks @j0Shi82 for sharing 👍
