### ISSUE TITLE
CORS - fetch API

### ISSUE THREAD

**Issue by nissamant** [QwikDev/partytown#341]
Hi Team,

We are trying to apply party town on the third party script which is from other domain. While party town gets executed, we are facing CORS issue due to inbuilt fetch API request.

Access-Control-Allow-Origin: * will not work for us due to strict security policy.

Any body faced before or is it an existing issue? Any alternative solution to fix the CORS for it.

**Comment by ashleyjlive** [comment]
Hey @nissamant,
The suggested approach is to create a proxy server that adjusts the Access-Control-Allow-Origin to something that fits within your policy (generally that would be a predefined hostname not a wildcard).
https://partytown.builder.io/proxying-requests
