### ISSUE TITLE
Support amazon publisher tag

### ISSUE THREAD

**Issue by vip30** [QwikDev/partytown#348]
**Is your feature request related to a problem? Please describe.**
After loading the apstag (https://c.amazon-adsystem.com/aax2/apstag.js) inside partytown, it throw error
![image](https://user-images.githubusercontent.com/4260833/213757266-235cd3dc-6cbc-435e-bcd4-79e7a5408e00.png)

and I wonder is partytown support function in function? (eg: `googletag.pubads().refresh`)

Reproduce url:
https://replit.com/@vip301/Amazon-Publisher-Tag-Partytown-Example

Seems currently the forward array are not quite supporting this scenario 

Thanks a lot!

**Comment by pm-harshad-mane** [comment]
@vip30 Please share the test page so that experts may be able to suggest the code change or config change.

**Comment by vip30** [comment]
https://replit.com/@vip301/Amazon-Publisher-Tag-Partytown-Example

here you are
