### ISSUE TITLE
Debugging not working

### ISSUE THREAD

**Issue by sushil-mirashi** [QwikDev/partytown#359]
I have enabled debugging and verbose level for devtools is also enabled still nothing is happening. Why ?

![image](https://user-images.githubusercontent.com/81154439/217237684-57371af5-4bbd-4749-8bd4-53d2f18963bd.png)

**Comment by sushil-mirashi** [comment]
> Can you show the value for `navigator.serviceWorker` from your console?

navigator.serviceWorker.getRegistrations().then(registrations => {
    console.log(registrations);
Tried above code and it is an empty array.
Service workers are not being registered so can you tell me the possible reason for that please

**Comment by sushil-mirashi** [comment]
> Can you show the value for `navigator.serviceWorker` from your console?

![image](https://user-images.githubusercontent.com/81154439/218407791-a88dfb0a-cfa7-4849-a6e8-4dddc4ad4b16.png)

navigator.serviceWorker.getRegistrations().then(registrations => {
    console.log(registrations);
Tried above code and it is an empty array.
Service workers are not being registered so can you tell me the possible reason for that please

**Comment by sushil-mirashi** [comment]
My project on local was virtual host and not localhost so when I changed that it started working....

**Comment by vinaygosain** [comment]
@sushil-mirashi please close this issue
