### ISSUE TITLE
Using Partytown when `script` already has a `type` defined

### ISSUE THREAD

**Issue by miina** [QwikDev/partytown#404]
I'm trying to use Partytown with [Marfeel which loads two scripts](https://community.marfeel.com/t/adding-marfeel-sdk-to-your-site/7478): one in ES5 and the other in ES6 where it's recommended to load the file of ES6 with `type="module"`.

Is there a way to still use it with Partytown while keeping "module" as type, too?

**Comment by jamaluddinrumi** [comment]
web worker does not support the use of module for now

https://github.com/BuilderIO/partytown/issues/195#issuecomment-1154275550
