### ISSUE TITLE
[🐞] Code script (gtag.js) is injected when we are using GTM

### ISSUE THREAD

**Issue by AbrahamIQConsulting** [QwikDev/partytown#456]
### Describe the bug

Implementing party town with GTM, this kind of script is injected in the browser:

<script type="text/partytown-x" src="https://www.googletagmanager.com/gtag/destination?id=G-AAAAA&amp;l=dataLayer&amp;cx=c"></script>

### Reproduction

private integration environment 

### Steps to reproduce

put type="text/partytown" with the script of GTM

<script type="text/partytown">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-XXXXX');</script>

After if we inspect the code we can see other script injected:

<script type="text/partytown-x" src="https://www.googletagmanager.com/gtag/destination?id=G-AAAAAA&amp;l=dataLayer&amp;cx=c"></script>

Testing only GTM without text/partytown this not happens in the site.

### Browser Info

Chrome

**Comment by thejackshelton** [comment]
Hey I created an empty astro app to try and replicate this behavior, the only script I saw other than an inline script was this:

![image](https://github.com/BuilderIO/partytown/assets/104264123/a900fc15-e4f6-4664-9a32-47ec92500fea)

Is this what you're talking about? I noticed the slugs are different.

**Comment by AbrahamIQConsulting** [comment]
Not, is exactly the GTag script that i shared. Other thing that i don't know if this is the reason. In GTM we have events and we add the GA4 by tag. Other thing that i don't mention before, is if i use the Google Tag Assistance plugin for chrome, this show an issue of implementation ( when this script injected in the header.)
