### ISSUE TITLE
[🐞] SleekNote: Promise not resolving correctly

### ISSUE THREAD

**Issue by Clonex** [QwikDev/partytown#460]
### Describe the bug

It throws some errors from within the SleekNote code, because `data` on `event` is undefined.
It originates from within the SleekNote script:
```javascript
window.SleekNote.API = new Promise((resolve) =>
    window.addEventListener('sleekNote', (event) => {
        event.data.type == "load" && resolve(event.data.command);
    })
);
```
This is the errors that is logged:
![image](https://github.com/BuilderIO/partytown/assets/408229/02d1a78e-62b6-4824-ae5b-2f568b8382b0)

### Reproduction

https://replit.com/join/ywfzymsqmc-clonex2

### Steps to reproduce

1. Go to [demo](https://partytown-sleeknote--clonex2.repl.co/).
2. Check console.

### Browser Info

Chrome 116.0.5845.141

**Comment by mhevery** [comment]
Thanks for the repro. It would help us a lot if you could open up a PR with the repro added to our tests, we could take it from there....

**Comment by Clonex** [comment]
> Thanks for the repro. It would help us a lot if you could open up a PR with the repro added to our tests, we could take it from there....

Sounds good! Made a PR with tests for Sleeknote. https://github.com/BuilderIO/partytown/pull/462

**Comment by mhevery** [comment]
I noticed you created and then closed a PR. Let me know if you need help.

**Comment by Clonex** [comment]
> I noticed you created and then closed a PR. Let me know if you need help.

I'm having problems finding a way to test it.. I've tried 2 methods now:
1. It sets some cookies on initilization.
2. It will create a iframe on initialzation.

But both of the cases happens before the error described.

It does expose a global `SleekNote` object, which also contains the Promise that throws (`SleekNote.API`). 
But that wouldnt be exposed, so im not sure if that could be a way of testing? 🤔 
![image](https://github.com/BuilderIO/partytown/assets/408229/43210d82-4ae4-44c9-8b6c-14112b6e73d5)

**Comment by mhevery** [comment]
Can't you just take your repro and graft it on top of our tests?
