### ISSUE TITLE
[🐞] Post integrating partytown, GA shows attributions being dropped.

### ISSUE THREAD

**Issue by topcoder87** [QwikDev/partytown#482]
### Describe the bug

we integrated partytown to offload GTM to secondary threads. Although we are seeing the needed improvements in overall performance, the forwarded GTM events are reporting a missing attribution.
Since we are very dependent on attributions to identify the source of the transaction etc.., this is becoming problematic for us.

Is there a way we can work around this one ?

### Reproduction

does not need one

### Steps to reproduce

1. setup GTM to run on secondary worker thread using partytown
2. check the google analytics dashboard to see attributions missing post implementation

### Browser Info

chrome, firefox, safari

**Comment by gioboa** [comment]
Thanks for the report, would you like to create a PR for that?
