### ISSUE TITLE
[🐞] Partytown doesn't work with Chatwoot 

### ISSUE THREAD

**Issue by FRNDLab** [QwikDev/partytown#515]
### Describe the bug

In the video, I create a chatwoot instance, and then I execute $chatwoot.toggle(); to show it.

The widget is transparent because partytown modify iframe.

https://github.com/BuilderIO/partytown/assets/102629955/d42b1518-d5d2-4fbc-a872-52dd312d7712

### I think the problem is in iframe

_with partytown_
![image](https://github.com/productdevbookcom/chatwoot/assets/102629955/6b7bf6db-59b7-4d22-b018-1714643bdf53)

_without partytown_
![image](https://github.com/BuilderIO/partytown/assets/102629955/43788f0f-fa34-45a5-b3e2-7b99759a22f3)

### NUXT 3 
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    "nuxt-purgecss",
    "@nuxt/image",
    "@nuxtjs/partytown",
    "@productdevbook/chatwoot",
  ],
  partytown: {
    debug: true,
    forward: [
      "chatwootSDK.run",
      "chatwootSDK.run",

      "$chatwoot.toggle",
      "$chatwoot.toggle",

      "$chatwoot.isOpen",
      "$chatwoot.isOpen",

      "$chatwoot.websiteToken",
      "$chatwoot.websiteToken",
    ],
  },

.....

  chatwoot: {
    init: {
      websiteToken: "exampleToken",
      baseUrl: "https://chat.hostname.com",
    },
    // If this is loaded you can make it true, https://github.com/nuxt-modules/partytown
    partytown: true,
  },
});
```

### Reproduction

N/A

### Steps to reproduce

N/A

### Browser Info

Edge

### partytown 0.8.1

**Comment by gioboa** [comment]
Hi @mariofernandu, can you create a specific test in the codebase to reproduce this case pls?

**Comment by mariofernandu** [comment]
Hi thanks for your time and help

You can download the code of the test here

https://issue515.clotrservers.com/partytown-issue-515.zip

and view live here: 

https://issue515.clotrservers.com/index.html

**Comment by mariofernandu** [comment]
> Hi @mariofernandu, can you create a specific test in the codebase to reproduce this case pls? A vanilla JS one will be awesome, thanks

Hi thanks for your time and help

You can download the code of the test here

https://issue515.clotrservers.com/partytown-issue-515.zip

and view live here: 

https://issue515.clotrservers.com/index.html
