### ISSUE TITLE
[✨] Magento 2 integration

### ISSUE THREAD

**Issue by rostilos** [QwikDev/partytown#527]
### Is your feature request related to a problem?

Magento 2 integration request

### Describe the solution you'd like

Hi!
I work in a company that develops projects on magento 2, and not so long ago I discovered partytown library that I would like to use during optimisation on some projects.
Unfortunately I didn't find official partytown support for magento 2, so I wrote a small support module ( https://github.com/rostilos/perspective-partytown ) . But I would like to have an official integration among other things. Would you be interested in this?

### Describe alternatives you've considered

https://github.com/rostilos/perspective-partytown

**Comment by gioboa** [comment]
Hi @rostilos that's great.
A guide on how integrate Magento will be amazing.
How can I test it?
Can you describe the minimal steps please?

**Comment by rostilos** [comment]
For testing first of course we will have to deploy magento2 on a local machine. 
The following CLI utility can help with this: 
https://github.com/wardenenv/warden-env-magento2
https://docs.warden.dev/environments/magento2.html

Next, it will be necessary to connect gtm to the site, with ga, fb pixel, hubspot (at least something from this list) included in it.

After that you will need to start a reverse proxy ( I used cloudflare-workers for that ).

then configure the settings of the module itself ( everything is intuitive there, there is an option to configure via admin panel, screenshot under the repository in git).

After that you can test it

**Comment by gioboa** [comment]
It sounds great. Would you like to drop a PR to describe the Magento integration steps?

**Comment by rostilos** [comment]
Yeah, I'll try to make time next week.

**Comment by rostilos** [comment]
Let me clarify : do you want a complete list of steps to reproduce how this can be implemented in M2 ( including the deployment of M2 itself on the local environment ) ?

**Comment by gioboa** [comment]
Yep, I think the same. We need to have the full integration before creating the docs page. You can look at the other integrations i.e. [Shopify Hydrogen](https://partytown.builder.io/shopify-hydrogen)
The M2 setup could be taken for granted.

**Comment by JMLucas96** [comment]
Any updates on this?

**Comment by rostilos** [comment]
@JMLucas96 
I'll probably look into it in the future, but at the moment I'm pretty busy with my main job.
You can try to use the compatibility module from the repository at the link from the top post

**Comment by rostilos** [comment]
As part of the MR that was accepted edits were added ( implementation documentation for Magento 2 platform ).
Despite the fact that the documentation is in the repository - it is still not on the documentation site. Then I couldn't find where to add these links and assumed it was not done within the repository
https://github.com/QwikDev/partytown/pull/594

**Comment by gioboa** [comment]
Thanks for your feedback. I added the missing link. Here is the [Magento 2](https://partytown.qwik.dev/magento2/) page.
