### ISSUE TITLE
[📖] Discord server link is broken

### ISSUE THREAD

**Issue by n0th1ng-else** [QwikDev/partytown#547]
### Suggestion

Hello team. I am reading the CONTRIBUTING.md file and it looks like the Discord invitation link is broken now. (ref: https://github.com/BuilderIO/partytown/blob/main/CONTRIBUTING.md#local-development)

Could you please check? Is Discord still a thing? Would be nice to clarify this. 

Thank you!

**Comment by gioboa** [comment]
Thanks. I'll fix it.
