### ISSUE TITLE
[🐞] Setup the Server for Reverse Proxy with Facebook Pixell

### ISSUE THREAD

**Issue by muhsin-life** [QwikDev/partytown#647]
### Describe the bug

In your test integration for the Facebook Pixel, I expected the reverse proxy setup to work with my custom proxy by correctly configuring the Access-Control-Allow-Origin header. However, despite these changes, only the reverse proxy provided by https://cdn.builder.io/api/v1/proxy-api appears to work.

`resolveUrl(url, location) {  
  if (url.hostname.includes('connect.facebook.net')) {  
    const proxyUrl = new URL('https://cdn.builder.io/api/v1/proxy-api');  
    proxyUrl.searchParams.append('url', url);  
    return proxyUrl;  
  }  
}`  

I attempted to create my own proxy with corrected headers, but events did not fire correctly. Is there anything beyond the reverse proxy setup you're doing to ensure events work?

### Reproduction

https://partytown.builder.io/tests/integrations/facebook-pixel/

### Steps to reproduce

1. Follow the test integration outlined here: [Facebook Pixel Integration Test](https://partytown.builder.io/tests/integrations/facebook-pixel/)
2. Implement a custom proxy server with the necessary CORS headers.
3. Attempt to track events using the Facebook Pixel through the custom proxy.

### Browser Info

Browser: Chrome , Operating System: Windows 11

**Comment by muhsin-life** [comment]
### API Handler (Nuxt 3)

```js
export default defineEventHandler(async (event) => {
  const query = getQuery(event);
  const url = String(query?.url) || null;

  if (!url || !url.includes("connect.facebook.net")) {
    throw createError({ status: 500 });
  }

  const data = await useStorage("assets:server").getItem(`reverse-proxy.js`);

  setResponseHeaders(event, {
    "Access-Control-Allow-Origin": "*", // Ensures CORS is properly handled
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "POST, GET, OPTIONS, PUT, DELETE",
    "Content-Type": "application/x-javascript; charset=utf-8",
    "Cache-Control": "public, max-age=5, s-maxage=5, stale-if-error=2678400, stale-while-revalidate=86400",
  });

  return data;
});
```

### Partytown Configuration

```js
partytown: {
  forward: ["fbq"], 
  resolveUrl: function (url: URL, location) {
    if (url.hostname.includes("connect.facebook.net")) {
      const proxyUrl = new URL("/api/v1/proxy-api");
      proxyUrl.searchParams.append("url", url.toString());
      return proxyUrl;
    }
  }
}
```

**Comment by muhsin-life** [comment]
I managed to resolve the issue by identifying that different files are served for specific URLs. Here's the updated API handler:

```js
export default defineEventHandler(async (event) => {
  const query = getQuery(event);

  const url = String(query?.url) || null;

  if (!url || !url?.includes("connect.facebook.net")) {
    throw createError({
      status: 500,
    });
  }

  // Serve different files based on the requested URL
  const assetsFile = url.includes("connect.facebook.net/en_US/fbevents.js")
    ? "events-file.js" // Serves the content of https://connect.facebook.net/en_US/fbevents.js
    : "reverse-proxy.js"; // Serves the saved content of https://cdn.builder.codes/api/v1/proxy-api?url=...

  const data = await useStorage("assets:server").getItem(assetsFile);

  setResponseHeaders(event, {
    "Access-Control-Allow-Origin": "*", // Ensures proper CORS handling
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "POST, GET, OPTIONS, PUT, DELETE",
    "Content-Type": "application/x-javascript; charset=utf-8",
    "Cache-Control":
      "public, max-age=5, s-maxage=5, stale-if-error=2678400, stale-while-revalidate=86400",
  });

  return data;
});
```


  - If the requested URL is `connect.facebook.net/en_US/fbevents.js`, the server serves `events-file.js` (which mirrors the content of `https://connect.facebook.net/en_US/fbevents.js`).
  - For other URLs under `connect.facebook.net`, it serves `reverse-proxy.js` the content similar to this https://cdn.builder.codes/api/v1/proxy-api?url=https%3A%2F%2Fconnect.facebook.net%2Fsignals%2Fconfig%2F166730740625110%3Fv%3D2.9.178%26r%3Dstable%26domain%3Dpartytown.builder.io%26hme%3D28abfdc7e582ae2a8fdd6ac5ebb406923cf601dc2ee488049b0628e75e0f6b36%26ex_m%3D70%252C122%252C107%252C111%252C61%252C4%252C100%252C69%252C16%252C97%252C89%252C51%252C54%252C173%252C176%252C188%252C184%252C185%252C187%252C29%252C101%252C53%252C77%252C186%252C168%252C171%252C181%252C182%252C189%252C132%252C41%252C191%252C192%252C34%252C144%252C15%252C50%252C197%252C196%252C134%252C18%252C40%252C1%252C43%252C65%252C66%252C67%252C71%252C93%252C17%252C14%252C96%252C92%252C91%252C108%252C52%252C110%252C39%252C109%252C30%252C94%252C26%252C169%252C172%252C141%252C86%252C56%252C84%252C33%252C73%252C0%252C95%252C32%252C28%252C82%252C83%252C88%252C47%252C46%252C87%252C37%252C11%252C12%252C13%252C6%252C7%252C25%252C22%252C23%252C57%252C62%252C64%252C75%252C102%252C27%252C76%252C9%252C8%252C80%252C48%252C21%252C104%252C103%252C105%252C98%252C10%252C20%252C3%252C38%252C74%252C19%252C5%252C90%252C81%252C44%252C35%252C85%252C2%252C36%252C63%252C42%252C106%252C45%252C79%252C68%252C112%252C60%252C59%252C31%252C99%252C58%252C55%252C49%252C78%252C72%252C24%252C113


This solution worked perfectly in my case. Closing the issue now. Thanks!

**Comment by gioboa** [comment]
Thanks @muhsin-life for the update, can we improve PartyTown docs with your findings?

**Comment by muhsin-life** [comment]
Sure! It's so nice to hear that my findings could help improve the PartyTown docs. I'd be happy to contribute or share more details if needed! Let me know how I can assist further. 😊

**Comment by gioboa** [comment]
@muhsin-life Can you open a PR to update the docs please?
